---
- name: Provision Ubuntu EC2
  hosts: ubuntu
  become: true

  tasks:
    - name: Update APT
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Ensure NGINX is running
      service:
        name: nginx
        state: started
        enabled: true

    - name: Create a custom index page
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <body>
          <h1>Hello from Ansible on Ubuntu!</h1>
          </body>
          </html>
